isTrain: true
iterations: 80000           # total iteration steps
save_freq: 1000             # The number of ckpt_save_freq
init_iters: 4000

# -------------------------optimizer---------------------------

lr_policy: step # linear | step | cosine
lr_init: 2.e-4 # The learning rate of initialization
lr_g: 2.e-4 # The learning rate of g
lr_d: 4.e-4 # The learning rate of d
lr_beta1_g: 0.5 # adam optimizer's momentum
lr_beta1_d: 0.5 # adam optimizer's momentum

# -------------------------weights---------------------------

g_adv_weight: 300.0 # Weight about GAN
d_adv_weight: 300.0 # Weight about GAN
# 1.5 for Hayao, 2.0 for Paprika, 1.2 for Shinkai
con_weight: 1.5 # Weight about VGG19
# 2.5 for Hayao, 0.6 for Paprika, 2.0 for Shinkai
sty_weight: 2.5 # Weight about style
# 15. for Hayao, 50. for Paprika, 10. for Shinkai
color_weight: 10. # Weight about color
# 1. for Hayao, 0.1 for Paprika, 1. for Shinkai
tv_weight: 1. # Weight about tv

# -------------------------network---------------------------

gan_loss: lsgan # [gan / lsgan / wgan-gp / wgan-lp / dragan / hinge]
img_ch: 3 # The size of image channel
img_size: 256 # The size of image: H and W
ch: 64 # base channel number per layer
d_layers: 3 # The number of discriminator layer
use_sn: true


